apiVersion: v1
kind: Service
metadata:
  name: myloginapp
  labels:
    app: myjavaapp
    version: 1.1.1
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
    version: 1.1.1
